return {
  { "friendly-snippets",     enabled = false },
  -- { "nvim-cmp",              enabled = false },
  -- { "cmp-nvim-lsp",          enabled = false },
  -- { "cmp-buffer",            enabled = false },
  -- { "cmp-path",              enabled = false },
  { "nvim-snippets",         enabled = false },
  -- { "mini.pairs",            enabled = false },
  -- { "ts-comments.nvim",      enabled = false },
  -- { "mini.ai",               enabled = false },
  -- { "lazydev.nvim",          enabled = false },
  -- { "nvim-lint",             enabled = false },
  -- { "nvim-lspconfig",        enabled = false },
  -- { "mason.nvim",            enabled = false },
  -- { "mason-lspconfig.nvim",  enabled = false },
  -- { "nvim-treesitter-textobjects", enabled = false },
  -- { "nvim-ts-autotag",       enabled = false },
}
